// <auto-generated />
using System;
using BarkodluSatis.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarkodluSatis.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230814061711_sabitkdvbanka")]
    partial class sabitkdvbanka
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarkodluSatis.Dal.Barkod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarkodNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("barkods");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.HizliUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hizliUruns");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IslemNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ıslems");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.IslemOzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AlisFiyatToplam")
                        .HasColumnType("float");

                    b.Property<byte>("Gelir")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Gider")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Iade")
                        .HasColumnType("tinyint");

                    b.Property<int>("IslemNo")
                        .HasColumnType("int");

                    b.Property<double>("Kart")
                        .HasColumnType("float");

                    b.Property<string>("Kullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nakit")
                        .HasColumnType("float");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ıslemOzets");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Sabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KartKomisyon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("sabits");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Satis", b =>
                {
                    b.Property<int>("SatisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AlisFiyat")
                        .HasColumnType("float");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Iade")
                        .HasColumnType("tinyint");

                    b.Property<int?>("IslemId")
                        .HasColumnType("int");

                    b.Property<int>("IslemNo")
                        .HasColumnType("int");

                    b.Property<double>("KdvTutari")
                        .HasColumnType("float");

                    b.Property<string>("Kullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SatisFiyat")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("Toplam")
                        .HasColumnType("float");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunGrup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SatisId");

                    b.HasIndex("IslemId");

                    b.ToTable("satis");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunGrup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("stokHarekets");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Terazi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeraziÖnEk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Terazis");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AlisFiyat")
                        .HasColumnType("float");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("int");

                    b.Property<double>("KdvTutari")
                        .HasColumnType("float");

                    b.Property<string>("Kullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<double>("SatisFiyat")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunGrup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunId");

                    b.ToTable("Uruns");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.UrunGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UrunGrupAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("urunGrups");
                });

            modelBuilder.Entity("BarkodluSatis.Dal.Satis", b =>
                {
                    b.HasOne("BarkodluSatis.Dal.Islem", "Islem")
                        .WithMany("Satislar")
                        .HasForeignKey("IslemId");
                });
#pragma warning restore 612, 618
        }
    }
}
